### ISSUE TITLE
App Check - Recaptcha in Production

### ISSUE THREAD

**Issue by JershDervis** [JershDervis/khione5#1]
recaptcha__en.js:201 Uncaught (in promise) Error: Missing required parameters: sitekey
    at iw.<anonymous> (recaptcha__en.js:201:214)
    at new iw (recaptcha__en.js:426:135)
    at T4.<anonymous> (recaptcha__en.js:177:446)
    at new T4 (recaptcha__en.js:721:472)
    at recaptcha__en.js:204:231
    at Ps (__layout.svelte-460dad55.js:198:749)
    at __layout.svelte-460dad55.js:198:337

**Comment by JershDervis** [comment]
<img width="712" alt="image" src="https://user-images.githubusercontent.com/12910980/175041239-22208af3-477b-49eb-9e27-ba5318daa763.png">
